before_script:
  ## Prepare for Deploy Keys
  ## see https://docs.gitlab.com/ee/ci/ssh_keys/README.html#ssh-keys-when-using-the-docker-executor
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config


pandocker:
  stage: build
  image: dalibo/pandocker:no-entrypoint
  script:
    #
    # The dalibo themes are not mandatory
    # CI should be able to run without it
    #
    - > 
        if [[ $GITLAB_DEPLOY_PRIVATE_KEY ]] ; then 
                ssh-add <(echo "$GITLAB_DEPLOY_PRIVATE_KEY")
                git clone -b stable git@gitlab.dalibo.info:marketing/themes.git
                make --directory=themes install
        fi
    #
    # pandoc
    # 
    - make all

  artifacts:
    paths:
      - fr/
      - en/
    expire_in: 1 day

#
# Publish the master branch
#    
publish:
  stage: deploy
  image: dalibo/pandocker:no-entrypoint
  script:
    ## Install Deploy Key
    - ssh-add <(echo "$CLOUD_DEPLOY_PRIVATE_KEY")
    ## Push
    - rsync -avp fr $CLOUD_DEPLOY_DEST 
    - rsync -avp en $CLOUD_DEPLOY_DEST
  only:
    - master@formation/workshops


